create table if not exists pedidos (
    id bigint generated by default as identity primary key,
    nome varchar(100) not null,
    quantidade int not null check (quantidade > 0),
    valor_total decimal(10, 2) not null check (valor_total > 0)
)